In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_excel("C:\\Users\\ASUS\\Downloads\\TRAIN_final.xlsx", index_col = "id")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48030 entries, 11651 to 89883
Data columns (total 49 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   label                      48030 non-null  int64  
 1   time_trans                 48030 non-null  float64
 2   cat_1                      48030 non-null  int64  
 3   cat_2                      48030 non-null  int64  
 4   cat_3                      48030 non-null  int64  
 5   cat_5                      48030 non-null  int64  
 6   mul_rate                   48030 non-null  float64
 7   value                      48030 non-null  int64  
 8   cat_6                      48030 non-null  int64  
 9   num_date_review            48030 non-null  int64  
 10  review_value               48030 non-null  int64  
 11  dob                        48030 non-null  int64  
 12  sex                        48030 non-null  int64  
 13  location_id                48030 non-null 

In [4]:
#Chọn biến cho x và y
ft = ['time_trans','job','unknown_var_2','unknown_var_4','unknown_var_5','unknown_var_7','unknown_var_9','unknown_var_10','unknown_var_17','social_friend_count']
x= data[ft]
y= data['label']
x.info

<bound method DataFrame.info of        time_trans  job  unknown_var_2  unknown_var_4  unknown_var_5  \
id                                                                    
11651    3.681389    1              7              1              1   
48491    3.681389    1             11              5              1   
42868    0.000000    3              4              1              3   
68835    3.681389    1              4              1              2   
73688    3.681389    1              5              1              9   
...           ...  ...            ...            ...            ...   
89571  643.028611    1              1              1              0   
89621    3.681389    1              1              1              0   
89649    3.681389    1              1              1              0   
89826    3.681389    1              1              1              0   
89883    3.681389    7              1              1              0   

       unknown_var_7  unknown_var_9  unknown

In [5]:

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [6]:
#chia dataset thành 2 tập là train và valid
X_train, X_valid, y_train, y_valid= train_test_split(x,y, train_size = 0.8, test_size=0.2, random_state=0)

In [7]:
X_valid.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9606 entries, 62181 to 59495
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   time_trans           9606 non-null   float64
 1   job                  9606 non-null   int64  
 2   unknown_var_2        9606 non-null   int64  
 3   unknown_var_4        9606 non-null   int64  
 4   unknown_var_5        9606 non-null   int64  
 5   unknown_var_7        9606 non-null   int64  
 6   unknown_var_9        9606 non-null   float64
 7   unknown_var_10       9606 non-null   int64  
 8   unknown_var_17       9606 non-null   int64  
 9   social_friend_count  9606 non-null   int64  
dtypes: float64(2), int64(8)
memory usage: 825.5 KB


In [8]:
#MÔ HÌNH DECISION TREE
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier(random_state=1)

In [9]:
#đưa dữ liệu train vào mô hình
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=1)

In [10]:
#Đưa ra dự đoán cho valid set
y_preds = dt_model.predict(X_valid)
y_preds

array([1, 0, 0, ..., 1, 1, 0], dtype=int64)

In [11]:
print('Accuracy score:', accuracy_score(y_valid, y_preds))
print(classification_report(y_valid, y_preds))

Accuracy score: 0.5554861544867791
              precision    recall  f1-score   support

           0       0.66      0.67      0.67      6335
           1       0.34      0.32      0.33      3271

    accuracy                           0.56      9606
   macro avg       0.50      0.50      0.50      9606
weighted avg       0.55      0.56      0.55      9606



In [12]:
#RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier

In [13]:
rf_model= RandomForestClassifier(random_state=1)

In [14]:
rf_model.fit(X_train,y_train)
rf=rf_model.predict(X_valid)
rf

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [15]:
print('Accuracy score:', accuracy_score(y_valid, rf))
print(classification_report(y_valid, rf))

Accuracy score: 0.6174266083697689
              precision    recall  f1-score   support

           0       0.66      0.87      0.75      6335
           1       0.34      0.13      0.19      3271

    accuracy                           0.62      9606
   macro avg       0.50      0.50      0.47      9606
weighted avg       0.55      0.62      0.56      9606



In [16]:
#LogisticRegression (TỆ KO DÙNG LUN ko phù hợp với bài toán)
from sklearn.linear_model import LogisticRegression

In [17]:
lr_model = LogisticRegression(random_state=1)

In [18]:
lr_model.fit(X_train, y_train)
lr_model.score(X_train, y_train)

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6530293566520925

In [19]:
print('Coefficient: \n', lr_model.coef_)
print('Intercept: \n', lr_model.intercept_)

Coefficient: 
 [[ 2.18013425e-05 -1.99035587e-02 -6.06365930e-03 -5.16747865e-03
  -1.25107643e-02 -1.35333566e-03  3.84719229e-04  3.82483664e-04
  -1.96832297e-04 -4.76863730e-05]]
Intercept: 
 [-0.01074394]


In [20]:
lr= lr_model.predict(X_valid)
lr

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
print('Accuracy score:', accuracy_score(y_valid, lr))
print(classification_report(y_valid,lr))

Accuracy score: 0.6594836560483032
              precision    recall  f1-score   support

           0       0.66      1.00      0.79      6335
           1       0.50      0.00      0.00      3271

    accuracy                           0.66      9606
   macro avg       0.58      0.50      0.40      9606
weighted avg       0.61      0.66      0.52      9606



In [22]:
#GaussianNB (THẤP)
from sklearn.naive_bayes import GaussianNB

In [23]:
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
nb = nb_model.predict(X_valid)
nb

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [24]:
print('Accuracy score:', accuracy_score(y_valid, nb))
print(classification_report(y_valid, nb))

Accuracy score: 0.448157401623985
              precision    recall  f1-score   support

           0       0.65      0.35      0.46      6335
           1       0.34      0.64      0.44      3271

    accuracy                           0.45      9606
   macro avg       0.49      0.49      0.45      9606
weighted avg       0.54      0.45      0.45      9606



In [25]:
#svc (TỆ KO DÙNG LUN)
from sklearn.svm import SVC

In [26]:
svc_model=SVC()
svc_model.fit(X_train, y_train)
svc_model.score(X_train, y_train)
svc= svc_model.predict(X_valid)
svc 

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [27]:
print('Accuracy score:', accuracy_score(y_valid, svc))
print(classification_report(y_valid, svc))

Accuracy score: 0.6594836560483032
              precision    recall  f1-score   support

           0       0.66      1.00      0.79      6335
           1       0.00      0.00      0.00      3271

    accuracy                           0.66      9606
   macro avg       0.33      0.50      0.40      9606
weighted avg       0.43      0.66      0.52      9606



C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [28]:
#KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier

In [29]:
knn_model = KNeighborsClassifier(n_neighbors=6)
knn_model.fit(X_train, y_train)
knn= knn_model.predict(X_valid)
knn

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [30]:
print('Accuracy score:', accuracy_score(y_valid, knn))
print(classification_report(y_valid, knn))

Accuracy score: 0.6203414532583802
              precision    recall  f1-score   support

           0       0.66      0.88      0.75      6335
           1       0.33      0.11      0.17      3271

    accuracy                           0.62      9606
   macro avg       0.50      0.50      0.46      9606
weighted avg       0.55      0.62      0.55      9606



In [31]:
#GradientBoostingClassifier (TỆ)
from sklearn.ensemble import GradientBoostingClassifier

In [32]:
gb_model= GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=1, random_state=1)

In [33]:
gb_model.fit(X_train, y_train)
gb= gb_model.predict(X_valid)
gb

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [34]:
print('Accuracy score:', accuracy_score(y_valid, gb))
print(classification_report(y_valid,gb))

Accuracy score: 0.6583385384134915
              precision    recall  f1-score   support

           0       0.66      1.00      0.79      6335
           1       0.21      0.00      0.00      3271

    accuracy                           0.66      9606
   macro avg       0.43      0.50      0.40      9606
weighted avg       0.51      0.66      0.52      9606



In [35]:
pip install xgboost

Note: you may need to restart the kernel to use updated packages.


In [36]:
pip install --upgrade xgboost

In [37]:
#XGBoost (TỆ)
from xgboost import XGBClassifier

In [38]:
xgb_model = XGBClassifier()
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0, ...)

In [39]:
xgb = xgb_model.predict(X_valid)
xgb

array([0, 0, 0, ..., 0, 0, 0])

In [40]:
print('Accuracy score:', accuracy_score(y_valid, xgb))
print(classification_report(y_valid, xgb))

Accuracy score: 0.6471996668748699
              precision    recall  f1-score   support

           0       0.66      0.96      0.78      6335
           1       0.36      0.04      0.08      3271

    accuracy                           0.65      9606
   macro avg       0.51      0.50      0.43      9606
weighted avg       0.56      0.65      0.54      9606



In [41]:
#Dự đoán trên tập data mới ở đây là file test
new_data = pd.read_excel("C:\\Users\\ASUS\\Documents\\a.xlsx", index_col = "id")

In [42]:
prediction =dt_model.predict(new_data)
prediction

array([0, 0, 1, ..., 0, 1, 0], dtype=int64)

In [43]:
df = pd.DataFrame(prediction)
filepath= "C:\\Users\\ASUS\\Downloads\\Book1.xlsx"
df.to_excel(filepath, index=False)